[package]
name = "cc-server"
publish.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cc-api.workspace = true
cc-crypto.workspace = true
cc-storage.workspace = true
anyhow.workspace = true
axum.workspace = true
figment.workspace = true
serde.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "net", "time", "sync"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
cc-crypto.workspace = true
cc-domain.workspace = true
base64.workspace = true
cc-api.workspace = true
figment = { workspace = true, features = ["test"] }
tempfile.workspace = true

[lints]
workspace = true
